### ISSUE TITLE
Security - Google credentials still valid

### ISSUE THREAD

**Issue by sync** [nandorojo/nextjs-conf-22-example#1]
You have left your `google-services.json` files and `GoogleService-Info.plist` with valid credentials, that have yet to be revoked. Just flagging this making sure nobody uses it to do bad stuff.

**Comment by nandorojo** [comment]
yeah, these are just there for a test project without a payment method. i’ll revoke them though to be safe

**Comment by nandorojo** [comment]
revoked, thanks for looking out
